// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function toInputString(date) {
  if (date === undefined) {
    return "";
  }
  var date$1 = Caml_option.valFromOption(date);
  var year = (date$1.getFullYear() | 0).toString().padStart(4, "0");
  var month = ((date$1.getMonth() | 0) + 1 | 0).toString().padStart(2, "0");
  var day = (date$1.getDate() | 0).toString().padStart(2, "0");
  return year + "-" + month + "-" + day;
}

function toString(date) {
  var year = (date.getFullYear() | 0).toString().padStart(4, "0");
  var month = ((date.getMonth() | 0) + 1 | 0).toString().padStart(2, "0");
  var day = (date.getDate() | 0).toString().padStart(2, "0");
  return year + "-" + month + "-" + day;
}

export {
  toInputString ,
  toString ,
}
/* No side effect */
